services:
  backend:
    build: ../backend
    container_name: om_backend
    volumes:
      - ../backend/src:/src/src
    ports:
      - 8000:80
  backend-tools:
    build:
      dockerfile: ../dev/backend-tools-tests/Dockerfile
      context: ../backend
    container_name: om_backend-tools
    volumes:
      - ../backend/src:/src/src
      - ../backend/tasks.py:/src/tasks.py
      - ../backend/tests:/src/tests
    environment:
      DATABASE_URL: sqlite+pysqlite://///sr/src/backend/dev.db
      TEST_DATABASE_URL: sqlite+pysqlite://///src/tests/test.db