services:
  metrics:
    build: ..
    container_name: om_metrics
    volumes:
      - ../backend/src/offspot_metrics_backend:/usr/local/lib/python3.11/site-packages/offspot_metrics_backend
      - reverse-proxy-srv:/reverse-proxy-logs
      - logwatcher-data:/data/logwatcher
      - ./packages.yaml:/conf/packages.yaml
    command:
      - uvicorn
      - offspot_metrics_backend.entrypoint:app
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --reload
      - --reload-dir
      - /usr/local/lib/python3.11/site-packages/offspot_metrics_backend
    ports:
      - 127.0.0.1:8002:80
    environment:
      PACKAGE_CONF_FILE: /conf/packages.yaml
      PROCESSING_DISABLED: "True"
      DATABASE_URL: sqlite+pysqlite:////usr/local/lib/python3.11/site-packages/offspot_metrics_backend/dev.db
      LOG_LEVEL: DEBUG
  backend-tools:
    build:
      dockerfile: ../dev/backend-tools/Dockerfile
      context: ../backend
    container_name: om_backend-tools
    volumes:
      - ../backend/src:/src/src
      - ../backend/pyproject.toml:/src/pyproject.toml
      - ../backend/htmlcov:/src/htmlcov
      - ../backend/tasks.py:/src/tasks.py
      - ../backend/dev_tools:/src/dev_tools
      - ../backend/tests:/src/tests
      - reverse-proxy-srv:/reverse-proxy-logs
    environment:
      PROCESSING_DISABLED: "True"
      DATABASE_URL: sqlite+pysqlite:////src/src/offspot_metrics_backend/dev.db
      TEST_DATABASE_URL: sqlite+pysqlite:////src/tests/test.db
      LOG_INJECTOR_TARGET: /reverse-proxy-logs
      LOG_INJECTOR_TMP: /tmp/log_injector
  frontend-tools:
    build:
      dockerfile: ../dev/frontend-tools/Dockerfile
      context: ../frontend
    container_name: om_frontend-tools
    volumes:
      - ../frontend/public:/work/public
      - ../frontend/src:/work/src
    ports:
      - 127.0.0.1:8003:5173
  kiwix-serve:
    container_name: om_kiwix
    image: ghcr.io/offspot/kiwix-serve:3.5.0-2 # there is no more latest/dev version
    volumes:
      - ./zims:/data
    command:
      - kiwix-serve
      - /data/devops.stackexchange.com_en_all_2023-05.zim
      - /data/sqa.stackexchange.com_en_all_2023-05.zim
    ports:
      - 127.0.0.1:8001:80
  reverse-proxy:
    container_name: om_reverse-proxy
    image: caddy:2.6.1-alpine
    volumes:
      - ./reverse-proxy/config/Caddyfile:/etc/caddy/Caddyfile
      - ./file-browser-data:/file-browser-data
      - reverse-proxy-srv:/srv
    ports:
      - 127.0.0.1:8000:80
  edupi:
    container_name: om_edupi
    image: ghcr.io/offspot/edupi:dev
    ports:
      - 127.0.0.1:8004:80
    volumes:
      - edupi-data:/data
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
volumes:
  reverse-proxy-srv:
  logwatcher-data:
  edupi-data:
