name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3

      - name: Backend - Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64

      - name: Backend - Install dependencies
        run: |
          python -m pip install --upgrade pip invoke toml
          cd backend
          invoke install-deps --package dev

      - name: Backend - Unit tests with pytest
        run: |
          cd backend
          PYTHONPATH=src pytest tests/unit
