name: Pull Request

on:
  pull_request:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    # run CI job if the pull request originates from a fork (otherwise the CI is already triggered by the push to a branch)
    if: github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
